### ISSUE TITLE
How do you create time for research on a new project?

### ISSUE THREAD

**Issue by brianlovin** [designdetails/designdetails#325]
Asked anonymously: 

I'm a dual UI/UX Designer at a startup, and am wondering if you have any tips for asking for time to research on a new project? 

Just some background, I have been working on low fidelity and high fidelity wireframes for a couple days, and still need to do some research "in the wild" before we start building the product out. However, my project manager wants me to begin building components (buttons, etc) for the product as soon as possible. Although I have done research and design before, this is my first time in a UI/UX position and I am finding it difficult to balance what is being asked of me and what I know I need to do to make the product as successful as possible.

**Comment by gaurangalat** [comment]
There is no harm in asking for more time if you feel you are not ready (as they say, measure twice, cut once). Most importantly, identify what value that this additional research is going to deliver. Make sure that before you ask for additional time, you have a plan of action ready (next steps, what you plan to do, research methodology you might use, etc). Set tangible deadlines for yourself because it's usually hard to capture how much time is needed for researching. Talk to your project manager about the value this research phase is going to deliver, outline your next steps, and ask for a specific amount of time (x days/ by the end of x sprint). This will (hopefully) create a compelling case. 

Also, don't be afraid of reaching out to the design manager/ senior designer on your team.
