### ISSUE TITLE
The role of frontend tech debt in getting good design shipped

### ISSUE THREAD

**Issue by akhil-17** [designdetails/designdetails#424]
Bringing up a topic that I haven't seen discussed much and would love to spark a conversation around. 

Increasingly, I've found myself designing for products that have been around long enough that the interface has accumulated a significant chunk of frontend tech debt. They've usually been cobbled together with all kinds of frontend hacks that are difficult to maintain and update in the long run as the product matures and gets bloated with features.

I'm finding that when a product is in this state, I'm not able to successfully advocate for any big UI changes to get shipped due to the frontend engineers estimating the work to take a very long time — on the scale of months — in turn forcing the PM's hand to prioritize other higher impact work that those months could be used for instead. The pattern repeats and the design updates never get prioritized to be worked on.

Strategies that I've already tried:
- Breaking down the design work into stages and milestones. It's still a tricky sell to get it done if it doesn't neatly fit into a big project or feature that the team is working on. 

- Building relationships with the frontend engineers to get them to care about the design and presentation of the product they work, but it's been hit or miss depending on how passionate the engineers themselves are about it in the first place.

- Working with the frontend engineers to identify the riskiest pieces of the changes and to figure out what a pared down version of the design that could ship faster is. Even with this, it often results in some version of _"this specific thing is going to take a large cross-team effort that will take several weeks due to the way it's built"_.

 It's a surprisingly common and difficult situation, because even when the product and design teams are in agreement that an update desperately needs to be made, it ultimately boils down to the estimates of the frontend engineers as to whether or not the updated designs will ever see the light of day. Have you run into this? What are some other strategies to utilize here?

Thanks in advance.

**Comment by brandonread** [comment]
👋 Hey Akhil! Love these observations and your attempted strategies. There are a few different lenses through which one can view this problem–I'll respond with the one that's currently top of mind.

---

I think first it's important that both sides of this relationship have thorough, objective understandings of the respective domains (e.g. infra, debt, vision for both Design and Technical). This is already difficult: you need access to current, future, and historical knowledge of the decision-making and intent at both design and technical layers.

Accessing this information can be difficult if the knowledge has been lost due to team churn, lack of systems documentation, limited design/engineering industry (or team/project) experience, silo'd ownership, institutional incentive structures (e.g. written culture vs move-fast-and-break-things), and a confluence of other factors.

But let's say you have access to this shared understanding of the respective domains–at least current/historical knowledge. With this, you can start to work with engineering leadership to advocate for change. From the design side, it's important to define the systems you might create such that any investment on the engineering end will "automate" much of the development of the future for which you're advocating. This requires a deeper understanding of the technical systems that power the experience as it is today, as well as proposed requirements for the technical systems of tomorrow (this requires partnership with both Product and Engineering).

The systems you propose ought to be flexible, future-proof (within reason), and consumable–you're basically developing an API at this point, something on top of which you can ship modular design interventions at speed without the historical engineering pushback. With this proposal, you're petitioning for a multi-week/month/year-long re-architecture and rebuild from what exists today.

This work-stream may be consumed by one or many contributors–often thrashing between routine maintenance, bug-fixes, and feature additions toward the existing technology–with the potential for some or all (including engineering leadership/management/sponsorship) to churn throughout the duration. The team that starts the work may not be the team that completes the work. Written culture is important here. Additional friction may come from "extend existing" vs "full-rewrite" debates, as well as the associated pros/cons of either of those approaches whichever path is taken.

Stepping back for a moment, it's important to consider the most important part of this whole dance: persuasion. As the designer responsible for this product (or suite of interconnected experiences), you're the advisor to the team on where we're headed. When someone sees the grande vision, they think: "Oh, that looks neat", but rarely step beyond that to provide estimates of the work involved unless prompted top-down (e.g. CEO, VP, Director, Manager, etc). So you'll need to articulate a compelling vision not only to your PM and engineers, but also to the relevant Engineering Leadership who can activate workstreams in alignment with business and technical roadmaps.

This means spending time understanding what incentives drive the chain of influence that can earn you the buy-in you're seeking. Once you understand those, you'll want to tailor your pitches to the relevant audiences in alignment with those incentives (e.g. team level OKRs are useful, but calculating financial impact will likely be the more relevant driver). For example, if you know that your proposal will have some estimated result (speedup support resolution by 50%, leading to $X cost-savings per year), and can compare the cost of continuing down the path today (e.g. tradeoffs between competing initiatives, continued losses, etc) vs. the engineering cost (you'll want rough estimates from technical domain experts here), you'll be able to convince yourself and others of the impact (financial and otherwise) driven through this work-stream.

At this point, you might be thinking: "That sounds like a lot. That sounds slow." It is–to both of those. When a system is unhealthy, it may be expensive to heal. When an unhealthy system is pitted against hundreds of other unhealthy systems, it takes a miracle (or years) for one to be healed–and the healing sometimes comes in the form of that "full rewrite" mentioned above when debt is excruciatingly unbearable.

Stepping back again–further this time–we see there is a natural evolution and devolution of products and technologies over time, requiring different ways of contributing at each stage of the lifecycle.

For new products, everything moves fast–engineering is not a bottleneck. At this stage, you need generators–contributors who can pump out designs and code. Designers and developers often love this stage–greenfield projects are hot.

As the product matures, there are likely a few major changes that happen at both a presentational and architectural level. These contributors have more knowledge of where the product is headed, and where things broke down in the previous model. The difficulty of these initiatives varies–sometimes an org-wide design or technical solution can be leveraged to speedup development, while other times a new approach must be crafted from scratch. Centrally sponsored technologies are sometimes easy to adopt, while other times creating more headaches than anticipated. This thrash piles on over time. Sometimes, you're fortunate as a designer to lead one of the aforementioned overhauls. It can be painful, but personally rewarding, and valuable to the customer. Likewise for engineering.

Finally, products reach a maintenance stage–where contribution is slow–laden with process to ensure the house of cards remains intact while interacting with these degraded, loosely-understood systems. For contributors, these services require the ability to focus, follow rules, debug, and research. While this skillset could be routed with success toward developing new technologies, you're at this point waging a war with the OKRs and business-level systems and hierarchy already in motion, or instead at the mercy of the accumulated technical debt. Working on these systems can be debilitating for Designers/Engineers who like to move faster, or make major change. It is possible, but it's mentally exhausting. These contributors will occasionally leave the product vertical and instead join a centralized, horizontal team to solve one of the big pains they faced throughout their tour. This leads to eventually elevating all of those legacy, forgotten, and soul-sucking services across multiple teams and organizations which can be similarly rewarding, but through a different set of personal outcomes and career expectations.

---

I chose to respond from less of a solution-oriented space, and more of a macro/organizational dynamics-level. This has been my experience and observation, but I'm curious and open to hearing alternate perspectives. While what I shared has somewhat of a bleak tint, it's mostly a starting point to think about how to solve the challenges from a different angle–for example, how might we align hiring and project resourcing with career goals and skillsets such that the stages of product maturity and contributor strengths feel connected? How might we prioritize developer-experience for early-adopters of new technologies developed horizontally? How might we better understand our own personal and career goals, as well as the teams onto which we're hired so that we feel energized at work?

The most exciting thing to me about this thread is the massive opportunity in augmenting and reimagining the product development lifecycle/workflow to solve these challenges outlined above.

**Comment by akhil-17** [comment]
Love this incredibly detailed and thoughtful response! Glad you acknowledged the role of engineering documentation, staffing seniority, resourcing & turnover, ability to focus and not thrash during the work, and the necessity to actually have someone very high up activate the workstreams down the line. These are all highly variable depending on the company, culture, level of product maturity, the organizational processes, and the level to which knowledge is shared across the team.

It sounds like it's a great opportunity for designers looking to become leaders by flexing their persuasion skills and seeing if they can actually understand what drives and influences these disciplines that design ends up collaborating so closely with to actually build products. If I'm understand your overall point correctly, it's that the biggest roadblock standing in the way of getting these big frontend projects to happen is at the macro/organizational dynamics level, especially at larger companies. I'd agree with that. 

There seems to be a tendency for VPs/execs to focus on things like stock price (if public) and specific internal/external OKRs, and it's often incredibly challenging (if not impossible) to tie these redesign projects to these metrics. The more I try to speak their language and justify the value and ROI of doing it, the more I find that it's a skillset I maybe don't necessarily want to focus on. I'm at the point where I'm a mid-level/senior designer who's focusing on craft as an IC, and am coming to terms with what it means to specialize in certain aspects of leadership and what path that will put me on going forward. Really interesting to think about this in terms of personal careers and future growth potential, because the companies look at these in terms of risks, timelines, and metrics. And of course, our customers look at the products we're building through the lens of value, usefulness, and time saved. Really tricky balance to find (if it even exists).
