### ISSUE TITLE
How do you deal with random and out of scope ideas from stakeholders?

### ISSUE THREAD

**Issue by jessicaperelman** [designdetails/designdetails#524]
This happens to me all the time. We are in the middle of a project, we have already established goals and boundaries and scope and all of that and we are deciding between several potential solutions to explore further. And then it happens. Someone (usually someone higher up) starts to come up with ideas.

"What if we do this...?

Wouldn't it be cool if we did this...?

I just thought of something and I think we should do this...

I have a brilliant idea, or at least I think it is brilliant..."

Some of these ideas are not bad at all. The problem is that sometimes they are not relevant to the current project and are out of scope.

I really struggle with this. I can't just ignore them. I have tried to say something like "Absolutely! let's capture that idea somewhere, but it does not quite fit into the scope of this project". Sometimes this works, but sometimes it doesn't. Sometimes they start arguing and questioning the priorities and the scope of the project and they get defensive and more passionate about their own idea. And sometimes I feel like I may come across as a snub.

What do I need to do to prevent this from happening or manage the situation better when it does come up?

**Comment by tamara2153** [comment]
As Marshall and Brian mentioned in the pod, it happens to the best of us! 

I find it helpful to ask Why? Sometimes I feel like a five-year-old, but many times you can uncover some interesting stuff by just asking why. Why is it important? Why would it be cool? How would it contribute to our goals/metrics/strategy? Why should we prioritize this instead of all this other stuff. 

Not always, but sometimes they can talk themselves out of their own idea =) other times, you might discover that it's actually important and should be reprioritized.

**Comment by brianlovin** [comment]
Love that advice @tamara2153! 

Forgot to comment here as well saying that we discussed this in the latest episode: https://designdetails.fm/episodes/7y_EU59o

Closing this issue so it's easy for us to track, but feel free to keep the comments going here 😊
